CREATE DATABASE HighSchool
CREATE TABLE student(
SID INT(4) NOT NULL,
FName CHAR(25) NOT NULL,
LName CHAR(20) NOT NULL,
gender ENUM('M','F') DEFAULT 'M',
address VARCHAR(35) NOT NULL,
DOB DATE NOT NULL,
Email VARCHAR(20) NOT NULL,
contact VARCHAR(20) NOT NULL,
DateOfEnroll DATE NOT NULL,
PRIMARY KEY(SID)
);

CREATE TABLE Department(
DID INT(4) NOT NULL,
DName CHAR(25) NOT NULL,
Location VARCHAR(35) NOT NULL,
DOB DATE NOT NULL,
contact VARCHAR(20) NOT NULL,
ext CHAR(10) NOT NULL,
PRIMARY KEY(DID)
);

ALTER TABLE student
ADD COLUMN DID INT(4),
ADD FOREIGN KEY(DID) REFERENCES Department(DID);

CREATE TABLE courses(
CID INT(4) NOT NULL,
CName CHAR(25) NOT NULL,
CType ENUM('Core','Elective') DEFAULT 'Core',
TIME VARCHAR(20) NOT NULL,
Semester VARCHAR(20) NOT NULL,
Crhr ENUM('2','3') DEFAULT '3',
PRIMARY KEY(CID)
);

CREATE TABLE register(
regID INT(5) NOT NULL,
SID INT(4) NOT NULL,
CID INT(4) NOT NULL,
PRIMARY KEY(regID)
);

ALTER TABLE register
ADD FOREIGN KEY(SID) REFERENCES student(SID),
ADD FOREIGN KEY(CID) REFERENCES courses(CID)

CREATE TABLE sections(
secID INT(4) NOT NULL,
secName CHAR(25) NOT NULL,
Semester VARCHAR(20) NOT NULL,
SID INT(4) NOT NULL,
PID INT(4) NOT NULL,
DID INT(4) NOT NULL,
PRIMARY KEY(secID)
);

ALTER TABLE courses
ADD COLUMN secID INT(4) NOT NULL,
ADD FOREIGN KEY(secID) REFERENCES sections(secID);

CREATE TABLE professor(
PID INT(4) NOT NULL,
FName CHAR(25) NOT NULL,
LName CHAR(20) NOT NULL,
gender ENUM('M','F') DEFAULT 'M',
address VARCHAR(35) NOT NULL,
Email VARCHAR(20) NOT NULL,
contact VARCHAR(20) NOT NULL,
Joindate DATE NOT NULL,
salary INT(7) NOT NULL,
experience VARCHAR(10) NOT NULL,
DID INT(4) NOT NULL,
PRIMARY KEY(PID)
);

ALTER TABLE professor
ADD COLUMN secID INT(4) NOT NULL,
ADD FOREIGN KEY(secID) REFERENCES sections(secID);

ALTER TABLE professor
ADD FOREIGN KEY(DID) REFERENCES department(DID);

ALTER TABLE student
ADD COLUMN projID INT(4) NOT NULL,
ADD FOREIGN KEY(projID) REFERENCES fyp(projID);


CREATE TABLE degreeHolder(
degID INT(4) NOT NULL,
projID INT(4) NOT NULL,
title CHAR(20) NOT NULL,
dateOfissue DATE NOT NULL,
SID INT(4) NOT NULL,
PRIMARY KEY(degID)
);


CREATE TABLE Examination(
ExamID INT(4) NOT NULL,
CID INT(4) NOT NULL,
PID CHAR(20) NOT NULL,
DATE DATE NOT NULL,
SID INT(4) NOT NULL,
room VARCHAR(4) NOT NULL,
PRIMARY KEY(ExamID)
);

CREATE TABLE Stud_exam(
SID INT(4) NOT NULL,
ExamID INT(4) NOT NULL,
StudExamID INT(4) NOT NULL,
PRIMARY KEY (StudExamID),
FOREIGN KEY (SID) REFERENCES student(SID),
FOREIGN KEY (ExamID) REFERENCES Examination(ExamID)
);


ALTER TABLE student
ADD COLUMN degID INT(4) NOT NULL,
ADD FOREIGN KEY (degID) REFERENCES degreeHolder(degID)

ALTER TABLE student
ADD COLUMN DID INT(4),
ADD FOREIGN KEY(DID) REFERENCES Department(DID);

ALTER TABLE student
ADD FOREIGN KEY (degID) REFERENCES degreeHolder(degID)


ALTER TABLE register
ADD FOREIGN KEY(CID) REFERENCES courses(CID)


ALTER TABLE Stud_exam
ADD FOREIGN KEY (ExamID) REFERENCES Examination(ExamID)

ALTER TABLE sections
ADD FOREIGN KEY(PID) REFERENCES professor(PID)